export enum Breakthrough{
    ADVANCED_DRONE_DRIVE = "Advanced Drone Drive",
    ALIEN_IMPRINTS = "Alien Imprints",
    ANCIENT_TERRAFORMING_DEVICE = "Ancient Terraforming Device",
    ARTIFICIAL_MUSCLES = "Artificial Muscles",
    AUTONOMOUS_HUBS= "Autonomous Hubs",
    CAPTURE_ASTEROID= "Capture Asteroid",
    CARGO_BAY_OF_HOLDING= "Cargobay of holding",
    CLONING= "Cloning",
    CONSTRUCTION_NANITES= "Construction Nanites",
    CORE_METALS= "Core Metals",
    CORE_RARE_METALS= "Core Rare Metals",
    CORE_WATER= "Core Water",
    CRYO_SLEEP= "Cryo-sleep",
    DESIGNED_FORESTATION= "Designed Forestation",
    DOME_STREAMLINING= "Dome Streamlining",
    DRY_FARMING= "Dry Farming",
    ETERNAL_FUSION= "Eternal Fusion",
    EXTRACTOR_AI= "Extractor AI",
    FACTORY_AUTOMATION= "Factory Automation",
    FOREVER_YOUNG= "Forever Young",
    FRICTIONLESS_COMPOSITES= "Frictionless Composites",
    GEM_ARCHITECTURE= "Gem Architecture",
    GENE_SELECTION= "Gene Selection",
    GIANT_CROPS= "Giant Crops",
    GLOBAL_SUPPORT= "Global Support",
    GOOD_VIBRATIONS= "Good Vibrations",
    HIVE_MIND= "Hive Mind",
    HULL_POLARIZATION= "Hull Polarization",
    HYPERSENSITIVE_PHOTOVOLTAICS= "Hypersensitive Photovoltaics",
    INSPIRING_ARCHITECTURE= "Inspiring Architecture",
    INTERPLANETARY_LEARNING= "Interplanetary Learning",
    LAKE_VAPORATORS= "Lake Vaporators",
    LANDSCAPING_NANITES= "Landscaping Nanites",
    MAGNETIC_EXTRACTION= "Magnetic Extraction",
    MARS_MARKETING= "Mars Marketing",
    MARTIAN_DIET= "Martian Diet",
    MARTIAN_STEEL= "Martian Steel",
    MARTIANBORN_INGENUITY= "Martianborn Ingenuity",
    MOLE_PEOPLE= "Mole People",
    MULTISPIRAL_ARCHITECTURE= "Multispiral Architecture",
    NANO_REFINEMENT= "Nano Refinement",
    NEOCONCRETE= "Neo-Concrete",
    NEURAL_EMPATHY= "Neural Empathy",
    NOCTURNAL_ADAPTATION= "Nocturnal Adaptation",
    OVERCHARGE_AMPLIFICATIONS= "Overcharge Amplifications",
    PLASMA_ROCKET= "Plasma Rocket",
    PLUTONIUM_SYNTHESIS= "Plutonium Synthesis",
    PREFAB_COMPRESSION= "Prefab Compression",
    PRINTED_ELECTRONICS= "Printed Electronics",
    PROJECT_PHOENIX= "Project Phoenix",
    RAPID_SLEEP= "Rapid Sleep",
    RESILIENT_VEGETATION= "Resilient Vegetation",
    SAFE_MODE= "Safe Mode",
    SERVICE_BOTS= "Service Bots",
    SOYLENT_GREEN= "Soylent Green",
    SPACE_REHABILITATION= "Space Rehabilitation",
    SUPERCONDUCTING_COMPUTING= "Superconducting Computing",
    SUPERFUNGUS= "Superfungus",
    SUPERIOR_CABLES= "Superior Cables",
    SUPERIOR_PIPES= "Superior Pipes",
    SUSTAINED_WORKLOAD= "Sustained Workload",
    THE_POSITRONIC_BRAIN= "The Positronic Brain",
    VECTOR_PUMP= "Vector Pump",
    VEHICLE_WEIGHT_OPTIMISATIONS= "Vehicle Weight Optimizations",
    VOCATION_ORIENTED_SOCIETY= "Vocation-Oriented Society",
    WIRELESS_POWER= "Wireless Power",
    ZERO_SPACE_COMPUTING= "Zero-Space Computing"
};

export enum Variant {
    STANDARD = "Standard",
    GREEN_PLANET = "Green Planet",
    BELOW_BEYOND = "Below and Beyond",
    BEYOND_GREEN = "Beyond + Green",
    TITO_GREEN_PLANET = "Tito: Green Planet",
    EVANS_GREEN_PLANET = "Evans: Green Planet"
};

export type BreakthroughVariant = {
    breakthrough: Breakthrough;
    variant: Variant;
}

export const listBreakthroughVariant: BreakthroughVariant[] = [
    {breakthrough: Breakthrough.ADVANCED_DRONE_DRIVE, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.ALIEN_IMPRINTS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.ANCIENT_TERRAFORMING_DEVICE, variant: Variant.GREEN_PLANET},
    {breakthrough: Breakthrough.ARTIFICIAL_MUSCLES, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.AUTONOMOUS_HUBS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.CAPTURE_ASTEROID, variant: Variant.BELOW_BEYOND},
    {breakthrough: Breakthrough.CARGO_BAY_OF_HOLDING, variant: Variant.BELOW_BEYOND},
    {breakthrough: Breakthrough.CLONING, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.CONSTRUCTION_NANITES, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.CORE_METALS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.CORE_RARE_METALS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.CORE_WATER, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.CRYO_SLEEP, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.DESIGNED_FORESTATION, variant: Variant.GREEN_PLANET},
    {breakthrough: Breakthrough.DOME_STREAMLINING, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.DRY_FARMING, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.ETERNAL_FUSION, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.EXTRACTOR_AI, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.FACTORY_AUTOMATION, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.FOREVER_YOUNG, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.FRICTIONLESS_COMPOSITES, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.GEM_ARCHITECTURE, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.GENE_SELECTION, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.GIANT_CROPS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.GLOBAL_SUPPORT, variant: Variant.BELOW_BEYOND},
    {breakthrough: Breakthrough.GOOD_VIBRATIONS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.HIVE_MIND, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.HULL_POLARIZATION, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.HYPERSENSITIVE_PHOTOVOLTAICS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.INSPIRING_ARCHITECTURE, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.INTERPLANETARY_LEARNING, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.LAKE_VAPORATORS, variant: Variant.GREEN_PLANET},
    {breakthrough: Breakthrough.LANDSCAPING_NANITES, variant: Variant.GREEN_PLANET},
    {breakthrough: Breakthrough.MAGNETIC_EXTRACTION, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.MARS_MARKETING, variant: Variant.BELOW_BEYOND},
    {breakthrough: Breakthrough.MARTIAN_DIET, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.MARTIAN_STEEL, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.MARTIANBORN_INGENUITY, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.MOLE_PEOPLE, variant: Variant.BELOW_BEYOND},
    {breakthrough: Breakthrough.MULTISPIRAL_ARCHITECTURE, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.NANO_REFINEMENT, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.NEOCONCRETE, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.NEURAL_EMPATHY, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.NOCTURNAL_ADAPTATION, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.OVERCHARGE_AMPLIFICATIONS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.PLASMA_ROCKET, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.PLUTONIUM_SYNTHESIS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.PREFAB_COMPRESSION, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.PRINTED_ELECTRONICS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.PROJECT_PHOENIX, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.RAPID_SLEEP, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.RESILIENT_VEGETATION, variant: Variant.GREEN_PLANET},
    {breakthrough: Breakthrough.SAFE_MODE, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.SERVICE_BOTS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.SOYLENT_GREEN, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.SPACE_REHABILITATION, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.SUPERCONDUCTING_COMPUTING, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.SUPERFUNGUS, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.SUPERIOR_CABLES, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.SUPERIOR_PIPES, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.SUSTAINED_WORKLOAD, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.THE_POSITRONIC_BRAIN, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.VECTOR_PUMP, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.VEHICLE_WEIGHT_OPTIMISATIONS, variant: Variant.BELOW_BEYOND},
    {breakthrough: Breakthrough.VOCATION_ORIENTED_SOCIETY, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.WIRELESS_POWER, variant: Variant.STANDARD},
    {breakthrough: Breakthrough.ZERO_SPACE_COMPUTING, variant: Variant.STANDARD}
] as const;